appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.3.2
appReplicas: 2
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
  readinessProbe:
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:7000"]
  livenessProbe:
    exec:
      command: ["/bin/grpc_health_probe", "-addr=:7000"]
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi


servicePort: 7000
